#!/bin/bash

docker stop samrun || true
docker rm samrun || true
docker rmi sample || true

echo "FROM python:3" > Dockerfile

echo "RUN  pip install Flask" >> Dockerfile

echo "WORKDIR /home/app" >> Dockerfile

echo "COPY server.py" >> Dockerfile

echo "EXPOSE 5050" >> Dockerfile

echo "CMD python3 /home/app/server.py" >> Dockerfile

docker build -t sample .
docker run -t -d -p 5050:5050 --name samrun sample
